"""Axiom Zero — Phase 4: IR -> Lean 4 Compiler

Translates NormalizedIR, SpecCollection, and AbstractState into an idiomatic
Lean 4 module. For each function with specifications, generates:

1. A ``def`` for the function itself (the actual implementation).
2. Correctness theorems that reference the ``def`` by name, using the
   function's postcondition(s) as the claim.

Preconditions that are mere type assertions (e.g. ``isinstance(n, int)``)
are dropped because Lean's type system makes them redundant.
"""

from __future__ import annotations

import re
from typing import Any, Dict, List, Optional

from ast_extractor.ir import NormalizedIR, FunctionIR, StatementIR, ExpressionIR, ClassIR
from abstract_interpreter.abstract_domain import AbstractState
from spec_ingestion.obligations import ProofObligation, SpecCollection, ObligationKind


# ── Python -> Lean type mapping ──────────────────────────────────────────────

_PY_TYPE_TO_LEAN: Dict[str, str] = {
    "int": "\u2124", "Int": "\u2124",
    "float": "\u211d", "Float": "\u211d",
    "bool": "Bool", "Bool": "Bool",
    "str": "String", "String": "String",
    "None": "Unit", "NoneType": "Unit",
    "List": "List", "list": "List",
    "Dict": "HashMap", "dict": "HashMap",
    "Optional": "Option",
    "Set": "Set", "set": "Set",
    "Tuple": "Prod", "tuple": "Prod",
}

_BINOP_TO_LEAN: Dict[str, str] = {
    "+": " + ", "-": " - ", "*": " * ", "/": " / ",
    "//": " / ", "%": " % ", "**": " ^ ",
    "==": " = ", "!=": " \u2260 ",
    "<": " < ", "<=": " \u2264 ", ">": " > ", ">=": " \u2265 ",
    "and": " \u2227 ", "or": " \u2228 ", "in": " \u2208 ", "not in": " \u2209 ",
}

_UNOP_TO_LEAN: Dict[str, str] = {
    "-": "-", "not": "\u00ac", "~": "~~~",
}


# ── Difficulty classifiers ──────────────────────────────────────────────────

_SIMPLE_PATTERNS: List[str] = [
    r"^\s*\d+\s*[+\-*/]\s*\d+\s*[=<>!]?=\s*\d+\s*$",
    r"^\s*x\s*[+\-*/]\s*\d+\s*[=<>!]?=\s*\d+\s*$",
    r"^\s*\d+\s*[+\-*/]\s*x\s*[=<>!]?=\s*\d+\s*$",
    r"^\s*x\s*[+\-*/]\s*y\s*[=<>!]?=\s*[a-z]+\s*$",
    r"^\s*x\s*[=<>!]?=\s*\d+\s*$",
    r"^\s*x\s*[+\-*/]\s*0\s*[=<>!]?=\s*x\s*$",
    r"^\s*0\s*[+\-*/]\s*x\s*[=<>!]?=\s*x\s*$",
    r"^\s*x\s*-\s*x\s*[=<>!]?=\s*0\s*$",
    r"^\s*x\s*[*]\s*1\s*[=<>!]?=\s*x\s*$",
    r"^\s*1\s*[*]\s*x\s*[=<>!]?=\s*x\s*$",
    r"^\s*x\s*[=<>!]?=\s*x\s*$",
    r"^\s*x\s*>\s*0\s*$",
    r"^\s*x\s*<\s*0\s*$",
    r"^\s*x\s*>=\s*0\s*$",
    r"^\s*x\s*<=\s*0\s*$",
    r"^\s*loop_terminates",
    r"^\s*is_tensor",
]

_OMEGA_PATTERNS: List[str] = [
    r"^\s*\w+\s*[+]\s*\d+\s*>\s*\w+\s*$",
    r"^\s*\w+\s*[+]\s*\d+\s*>=\s*\w+\s*$",
    r"^\s*\w+\s*>\s*\d+\s*\u2192\s*\w+\s*>\s*0\s*$",
    r"^\s*\w+\s*[+]\s*\w+\s*[=<>!]?=\s*\w+\s*[+]\s*\w+\s*$",
    r"^\s*\w+\s*>\s*0\s*\u2192\s*-\w+\s*<\s*0\s*$",
    r"^\s*\w+\s*<\s*0\s*\u2192\s*-\w+\s*>\s*0\s*$",
]


class IRToLeanCompiler:
    """Translates NormalizedIR + SpecCollection into an idiomatic Lean 4 module.

    Each function produces:
      - A ``def`` implementing the function body.
      - A correctness theorem for each postcondition, referencing the def.
    Type-assertion preconditions (``isinstance``) are dropped.
    """

    def __init__(self) -> None:
        self._module_name = ""
        self._ir: Optional[NormalizedIR] = None
        self._specs: Optional[SpecCollection] = None
        self._abstract_state: Optional[AbstractState] = None

    def compile_module(
        self,
        ir: NormalizedIR,
        specs: SpecCollection,
        abstract_state: AbstractState,
        module_name: str = "target",
        module_doc: str = "",
    ) -> str:
        """Compile a full module into Lean 4 (function defs + correctness theorems)."""
        self._ir = ir
        self._specs = specs
        self._abstract_state = abstract_state
        self._module_name = module_name

        lines: List[str] = []
        doc = module_doc or f"Auto-generated by Axiom Zero from module: {module_name}"
        lines.append(f"/- {doc} -/")
        lines.append("")
        lines.append("import Mathlib")
        lines.append("")

        lines.extend(self._generate_content())
        return "\n".join(lines)

    # ── Content generation ────────────────────────────────────────────────

    def _generate_content(self) -> List[str]:
        """Generate function definitions followed by correctness theorems."""
        lines: List[str] = []
        lines.extend(self._generate_function_defs())
        if lines and lines[-1].strip():
            lines.append("")
        lines.extend(self._generate_correctness_theorems())
        return self._strip_trailing_empty_lines(lines)

    @staticmethod
    def _strip_trailing_empty_lines(xs: List[str]) -> List[str]:
        while xs and not xs[-1].strip():
            xs.pop()
        return xs

    # ── Step 1: Function definitions ──────────────────────────────────────

    def _generate_function_defs(self) -> List[str]:
        if not self._ir:
            return []
        lines: List[str] = []
        for func in self._ir.functions:
            lines.extend(self._generate_function_def(func))
            lines.append("")
        for cls in self._ir.classes:
            for method in cls.methods:
                lines.extend(self._generate_function_def(method, class_name=cls.name))
                lines.append("")
        return lines

    def _generate_function_def(self, func: FunctionIR, class_name: str = "") -> List[str]:
        """Generate a single ``def`` from a FunctionIR node."""
        func_name = f"{class_name}.{func.signature.name}" if class_name else func.signature.name

        # Determine which int params should be \u2115 (recursive + \u2265 0 precondition)
        nat_params = self._get_nat_params(func, func_name)

        # Parameter binders  (p : Type)
        param_binders: List[str] = []
        for param in func.signature.parameters:
            lean_type = self.translate_type(param.type.to_string()) if param.type else "\u2124"
            if lean_type == "\u2124" and param.name in nat_params:
                lean_type = "\u2115"
            param_binders.append(f"({param.name} : {lean_type})")
        all_params = " ".join(param_binders)

        return_type = self.translate_type(func.signature.return_type.to_string()) if func.signature.return_type else "\u2124"
        # For recursive functions with \u2115 params, convert the return type to \u2115 as well.
        # This avoids mixed-type coercions (e.g., ``n : \u2115`` but returning ``\u2124``),
        # which can cause fragile proofs and ambiguous coercions.
        if return_type == "\u2124" and nat_params:
            return_type = "\u2115"

        # Translate body
        body_expr = self._translate_body_to_expr(func.body)

        result: List[str] = []
        if len(param_binders) <= 2:
            result.append(f"def {func_name} {all_params} : {return_type} :=")
        else:
            result.append(f"def {func_name}")
            for b in param_binders:
                result.append(f"  {b}")
            result.append(f"  : {return_type} :=")

        result.append(f"  {body_expr}")

        # For recursive functions with \u2115 parameters, add a termination_by clause.
        # This tells Lean's termination checker to use the \u2115 parameter as the
        # decreasing measure, which makes patterns like ``if n = 0 then 1 else ...
        # n * factorial (n - 1)`` pass the termination check (since ``n - 1 < n``
        # for ``n > 0`` in \u2115).
        if nat_params:
            # Pick the first \u2115 parameter in declaration order as the
            # termination measure. This is deterministic and predictable.
            # For single-\u2115-param functions (the common case, e.g. factorial)
            # this is sufficient. For multiple \u2115 params, preferring the
            # first declaration-order param is the most likely decreasing one.
            term_param = next(
                (p.name for p in func.signature.parameters if p.name in nat_params),
                None,
            )
            if term_param:
                result.append(f"  termination_by {term_param}")

        return result

    def _translate_body_to_expr(self, body: List[StatementIR]) -> str:
        """Translate a list of statements into a single Lean expression."""
        if not body:
            return "sorry"

        # Single return statement
        if len(body) == 1 and body[0].stmt_type == "return":
            if body[0].value:
                return self.translate_expression(body[0].value)
            return "()"

        # If / else with explicit orelse branch
        if len(body) == 1 and body[0].stmt_type == "if" and body[0].orelse:
            cond = self.translate_expression(body[0].condition) if body[0].condition else "True"
            then_expr = self._translate_body_to_expr(body[0].body)
            else_expr = self._translate_body_to_expr(body[0].orelse)
            if then_expr and else_expr:
                return f"if {cond} then {then_expr} else {else_expr}"

        # If statement followed by more statements — recursive if-then-else chain
        # Handles patterns like:
        #   if c1: return a; if c2: return b; return c
        #   → if c1 then a else (if c2 then b else c)
        if body[0].stmt_type == "if":
            cond = self.translate_expression(body[0].condition) if body[0].condition else "True"
            then_expr = self._translate_body_to_expr(body[0].body)
            else_expr = self._translate_body_to_expr(body[1:])
            if then_expr:
                if else_expr:
                    return f"if {cond} then {then_expr} else {else_expr}"
                return f"if {cond} then {then_expr}"

        return "sorry  -- body translation not available"

    # ── Step 2: Correctness theorems ──────────────────────────────────────

    def _generate_correctness_theorems(self) -> List[str]:
        """Generate idiomatic correctness theorems that reference function defs.

        For each function with postconditions, emits:
            theorem <func>_correct (params) (hPreconditions) : <func> args <predicate>  :=  by
              <tactic>

        Preconditions that are type-assertions (isinstance) are dropped.
        The ``result`` placeholder in postconditions is replaced with the function call.
        """
        lines: List[str] = []
        if not self._specs or not self._ir:
            return lines

        # Group obligations by function name
        func_obligations: Dict[str, List[ProofObligation]] = {}
        for ob in self._specs.all:
            if ob.kind in (ObligationKind.PRECONDITION, ObligationKind.POSTCONDITION):
                func_obligations.setdefault(ob.function, []).append(ob)

        for func_name, obligations in func_obligations.items():
            func_ir = self._find_function(func_name)
            if not func_ir:
                continue

            # Separate non-type-assertion preconditions and postconditions
            preconditions: List[ProofObligation] = []
            postconditions: List[ProofObligation] = []
            for ob in obligations:
                if ob.kind == ObligationKind.PRECONDITION:
                    if self._is_type_assertion(ob.predicate):
                        print(f"[Axiom Zero] Dropped type-assertion precondition: '{ob.predicate}' "
                              f"(redundant in Lean; handled by type signature)")
                    else:
                        # Strip any isinstance/type calls from mixed preconditions
                        stripped_pred = self._strip_type_assertions(ob.predicate)
                        if stripped_pred:
                            ob.predicate = stripped_pred
                            preconditions.append(ob)
                elif ob.kind == ObligationKind.POSTCONDITION:
                    postconditions.append(ob)

            # Build the function-call string for replacing ``result``
            arg_names = [p.name for p in func_ir.signature.parameters]
            func_call = f"{func_name} {' '.join(arg_names)}"

            for i, post in enumerate(postconditions):
                theorem = self._build_correctness_theorem(
                    func_ir, func_name, func_call,
                    preconditions, post, i, len(postconditions),
                )
                if theorem:
                    lines.append(theorem)
                    lines.append("")

        return lines

    def _build_correctness_theorem(
        self,
        func_ir: FunctionIR,
        func_name: str,
        func_call: str,
        preconditions: List[ProofObligation],
        postcondition: ProofObligation,
        index: int,
        total: int,
    ) -> Optional[str]:
        """Build a single correctness theorem."""
        # Convert predicate to Lean syntax and replace ``result`` with function call
        cleaned_pred = self.obligation_to_predicate_lean(postcondition)
        cleaned_pred = re.sub(r'\bresult\b', func_call, cleaned_pred)
        # Split chained comparisons (a <= b <= c) into (a <= b) ∧ (b <= c)
        cleaned_pred = self._split_chained_comparisons(cleaned_pred)

        # Derive theorem name
        theorem_name = f"{func_name}_correct"
        if total > 1:
            theorem_name = f"{theorem_name}_{index}"

        # Compute the correct hypothesis name for preconditions
        hyp_name = "hpre" if len(preconditions) <= 1 else "h0"

        # Choose the best tactic
        tactic = self._select_tactic_for_predicate(func_name, cleaned_pred, func_ir, hyp_name)

        # Determine which int params should be \u2115 (recursive + \u2265 0 precondition)
        nat_params = self._get_nat_params(func_ir, func_name)

        # Build binder lines
        binder_lines: List[str] = []
        for param in func_ir.signature.parameters:
            lean_type = self.translate_type(param.type.to_string()) if param.type else "\u2124"
            if lean_type == "\u2124" and param.name in nat_params:
                lean_type = "\u2115"
            binder_lines.append(f"  ({param.name} : {lean_type})")

        # Add preconditions as hypotheses
        for pi, pre in enumerate(preconditions):
            lean_pre = self.obligation_to_predicate_lean(pre)
            hyp_name = f"h{pi}" if len(preconditions) > 1 else "hpre"
            binder_lines.append(f"  ({hyp_name} : {lean_pre})")

        # Emit the theorem
        result: List[str] = []
        if binder_lines:
            result.append(f"theorem {theorem_name}")
            result.extend(binder_lines)
            result.append(f"  : {cleaned_pred} :=")
        else:
            result.append(f"theorem {theorem_name} : {cleaned_pred} :=")

        if tactic and tactic != "sorry":
            result.append("  by")
            result.append(f"    {tactic}")
        else:
            result.append("  sorry")

        return "\n".join(result)

    def _select_tactic_for_predicate(self, func_name: str, pred: str, func_ir: Optional[FunctionIR] = None, hyp_name: str = "hpre") -> str:
        """Pick a proof tactic for a correctness theorem.

        Args:
            func_name: Name of the function being proved.
            pred: The predicate (postcondition) to prove.
            func_ir: The function IR for context (body inspection, etc.).
            hyp_name: Name of the precondition hypothesis (e.g. ``hpre`` or ``h0``).
        """
        stripped = pred.strip()
        # Strip any balanced outer parentheses for cleaner pattern matching
        while stripped.startswith("(") and stripped.endswith(")"):
            inner = stripped[1:-1].strip()
            if inner.count("(") == inner.count(")"):
                stripped = inner
            else:
                break

        # Detect whether this is a recursive function with \u2115 parameters.
        # Such functions need induction/cases-based tactics instead of
        # omega/simp, which cannot handle recursive calls.
        is_recursive_func = False
        nat_params: set[str] = set()
        term_param: Optional[str] = None
        body_has_cond = False
        body_uses_fdiv = False
        if func_ir is not None:
            is_recursive_func = self._is_recursive(func_ir)
            if is_recursive_func:
                nat_params = self._get_nat_params(func_ir, func_name)
                if nat_params:
                    term_param = next(
                        (p.name for p in func_ir.signature.parameters if p.name in nat_params),
                        None,
                    )
            # Check whether the function body contains if-expressions.
            # Functions without conditionals (e.g., a single ``a / b``)
            # don't need ``split_ifs`` in their proof tactics.
            body_has_cond = self._body_has_conditional(func_ir)
            # Check whether the function body uses floor division (``//``).
            # Functions using ``Int.fdiv`` need specialised lemmas.
            body_uses_fdiv = self._body_uses_fdiv(func_ir)

        # For recursive \u2115 functions with comparison goals (\u2265, >, \u2264, <),
        # use induction instead of omega — omega only handles linear arithmetic
        # and cannot reason about recursive definitions.
        if is_recursive_func and term_param and func_name in stripped:
            if any(op in stripped for op in ("\u2265", ">", "\u2264", "<")):
                return self._generate_induction_tactic(func_name, term_param)
            # For disjunction goals (e.g., ``(n = 0) \u2228 (factorial n = ...)``),
            # use case analysis on the \u2115 parameter instead of ``split_ifs``,
            # which is more robust and avoids fragile branching.
            if "\u2228" in stripped and func_name in stripped:
                return self._generate_cases_tactic(func_name, term_param)

        # rfl: equality where the function call appears on both sides or is definitionally equal
        # IMPORTANT: `` = `` must NOT match inside compound operators like ``>=``, ``<=``, ``!=``.
        # Use a regex with a negative lookbehind to skip those cases.
        if re.search(r'(?<![><!=]) = ', stripped) \
           and not any(c in stripped for c in ("\u2200", "\u2203", "\u2192", "\u2227", "\u2228")):
            left, right = stripped.split(" = ", 1)
            l, r = left.strip(), right.strip()
            if l == r:
                return "rfl"
            # Check for f(x) = x or f(x) = (x) or similar definitional equalities
            if l.startswith(f"{func_name} "):
                call_arg_str = l[len(func_name):].strip()
                # De-parenthesize RHS for comparison
                rhs = r
                while rhs.startswith("(") and rhs.endswith(")"):
                    inner = rhs[1:-1].strip()
                    if inner.count("(") == inner.count(")"):
                        rhs = inner
                    else:
                        break
                if call_arg_str == rhs:
                    return "rfl"                # Commutativity: check for a + b = b + a, a * b = b * a, etc.
                # This handles cases where f a b = b + a (commutativity of +/*)
                if l.startswith(f"{func_name} "):
                    call_args = l[len(func_name):].strip().split()
                    if len(call_args) >= 2:
                        a, b = call_args[0], call_args[1]
                        # De-parenthesize RHS for comparison
                        rhs = r
                        while rhs.startswith("(") and rhs.endswith(")"):
                            inner = rhs[1:-1].strip()
                            if inner.count("(") == inner.count(")"):
                                rhs = inner
                            else:
                                break

                        # f a b = b + a  (commutativity) → unfold f, then use add_comm/mul_comm
                        if rhs == f"{b} + {a}":
                            return f"simp [{func_name}, add_comm]"
                        if rhs == f"{b} * {a}":
                            return f"simp [{func_name}, mul_comm]"

                        # f a b = a + b  (matches function body) → definitional equality
                        if rhs == f"{a} + {b}":
                            return "rfl"
                        if rhs == f"{a} * {b}":
                            return "rfl"

                # Negation on the LHS (e.g., (¬ f(b)) = b) — rfl is wrong
                # Unfold the function and use simp (handles Bool double-negation)
                if "\u00ac" in l and func_name in l:
                    return f"simp [{func_name}]"

                # Fallback: rfl for simple equalities — Lean can unfold definitions
                if not any(c in r for c in ("\u2200", "\u2203", "\u2192", "\u2227", "\u2228")):
                    return "rfl"

        # omega: numeric inequalities / arithmetic
        for pattern in _OMEGA_PATTERNS:
            if re.match(pattern, stripped):
                return "omega"

        # simp: simple patterns that match after ``result`` → function-call substitution
        for pattern in _SIMPLE_PATTERNS:
            if re.match(pattern, stripped):
                return "simp"

        # Trivial proposition
        if stripped in ("True", "true"):
            return "trivial"

        # Function-call goal with comparison (likely a conditional definition)
        # If the predicate involves the function name plus a comparison (>=, >, <=, <),
        # unfold the definition and use omega. omega handles if-then-else internally,
        # so explicit split is not needed and avoids errors for non-conditional defs.
        if func_name in stripped and not any(c in stripped for c in ("\u2200", "\u2203", "\u2192", "\u2227", "\u2228")):
            if any(op in stripped for op in ("\u2265", ">", "\u2264", "<")):
                return f"unfold {func_name}; omega"

        # Negation equality involving a function call (e.g., (¬ f(b)) = b)
        # Unfold the function and use simp — handles Bool double-negation via simp
        if "\u00ac" in stripped and "=" in stripped and func_name in stripped:
            return f"simp [{func_name}]"

        # Function-call goal with pure conjunction (no disjunction), e.g.
        # ``lo <= f x ∧ f x <= hi``.
        # Typical for postconditions involving bounds like clamp.
        if "\u2227" in stripped and func_name in stripped and "\u2228" not in stripped:
            if body_uses_fdiv:
                # Function uses ``Int.fdiv`` (floor division).
                # Use the specialised Mathlib lemmas for integer floor division.
                # ``Int.fdiv_mul_add_fmod a b`` gives ``a.fdiv b * b + a.fmod b = a``
                # ``Int.lt_fdiv_add_one_mul_self a hb`` gives ``a < (Int.fdiv a b + 1) * b``
                # The precondition name is ``hpre`` (or ``h0`` for the first one).
                func_args = [p.name for p in func_ir.signature.parameters] if func_ir else []
                a_arg = func_args[0] if len(func_args) >= 1 else "a"
                b_arg = func_args[1] if len(func_args) >= 2 else "b"
                return (
                    f"unfold {func_name}; constructor\n"
                    f"    \u00b7 have h := Int.fdiv_mul_add_fmod {a_arg} {b_arg}\n"
                    f"      have hfmod_nonneg : 0 \u2264 Int.fmod {a_arg} {b_arg} :=\n"
                    f"        by\n"
                    f"          have h_eq : Int.fmod {a_arg} {b_arg} = Int.emod {a_arg} {b_arg} :=\n"
                    f"            Int.fmod_eq_emod_of_nonneg (le_of_lt {hyp_name})\n"
                    f"          rw [h_eq]\n"
                    f"          exact Int.emod_nonneg {a_arg} (ne_of_gt {hyp_name})\n"
                    f"      nlinarith\n"
                    f"    \u00b7 exact Int.lt_fdiv_add_one_mul_self {a_arg} {hyp_name}"
                )
            if not body_has_cond:
                # No if-expressions in body — ``split_ifs`` would be a no-op.
                # Use constructor with omega for non-recursive non-division goals.
                return f"unfold {func_name}; constructor <;> omega"
            return f"unfold {func_name}; split_ifs <;> constructor <;> linarith"

        # Function-call goal with mixed conjunction and disjunction
        # (e.g., ``(x < lo ∧ f x = lo) ∨ (x > hi ∧ f x = hi) ∨ (f x = x)``).
        # ``split_ifs`` provides hypotheses for each branch; ``solve_by_elim``
        # uses them to navigate the disjunction and close conjunction subgoals.
        if "\u2227" in stripped and "\u2228" in stripped and func_name in stripped:
            return f"unfold {func_name}; split_ifs <;> solve_by_elim"

        # Function-call goal with disjunction (e.g., f x = x ∨ f x = -x)
        # This is typical for functions defined by cases (like absolute value).
        if "\u2228" in stripped and func_name in stripped:
            return f"unfold {func_name}; split_ifs <;> simp"

        return "sorry"

    # ── Recursion & ℕ detection ────────────────────────────────────────

    @staticmethod
    def _expr_references_function(expr: Optional[ExpressionIR], func_name: str) -> bool:
        """Check if an expression tree contains a call to the given function name.

        Recursively walks all sub-expressions (left, right, operand, func, target,
        index, args, elements) looking for ``call`` nodes whose ``func.name``
        matches the target function name.
        """
        if expr is None:
            return False
        if expr.expr_type == "call":
            if expr.func and expr.func.expr_type == "variable" and expr.func.name == func_name:
                return True
        for attr in ("left", "right", "operand", "func", "target", "index"):
            child = getattr(expr, attr, None)
            if child is not None and IRToLeanCompiler._expr_references_function(child, func_name):
                return True
        for child in expr.args:
            if IRToLeanCompiler._expr_references_function(child, func_name):
                return True
        for child in expr.elements:
            if IRToLeanCompiler._expr_references_function(child, func_name):
                return True
        return False

    @staticmethod
    def _stmt_references_function(stmt: StatementIR, func_name: str) -> bool:
        """Check if a statement (or its sub-statements) references the given function."""
        for attr in ("value", "expression", "condition", "target"):
            expr = getattr(stmt, attr, None)
            if expr is not None and IRToLeanCompiler._expr_references_function(expr, func_name):
                return True
        for substmt in stmt.body + stmt.orelse:
            if IRToLeanCompiler._stmt_references_function(substmt, func_name):
                return True
        return False

    def _is_recursive(self, func: FunctionIR) -> bool:
        """Return True if the function body contains a direct recursive call."""
        func_name = func.signature.name
        for stmt in func.body:
            if self._stmt_references_function(stmt, func_name):
                return True
        return False

    @staticmethod
    def _body_has_conditional(func: FunctionIR) -> bool:
        """Return True if the function body contains if-expressions.

        This is used during tactic selection: functions without conditionals
        don't need ``split_ifs`` in their proof tactics. Walking the full
        statement tree covers nested ifs inside if-branches.
        """
        def _stmt_has_if(stmt: StatementIR) -> bool:
            if stmt.stmt_type == "if":
                return True
            for s in stmt.body + stmt.orelse:
                if _stmt_has_if(s):
                    return True
            return False
        for stmt in func.body:
            if _stmt_has_if(stmt):
                return True
        return False

    @staticmethod
    def _body_uses_fdiv(func: FunctionIR) -> bool:
        """Return True if the function body contains floor division (``//``).

        In Python, ``//`` is floor division which maps to ``Int.fdiv`` in Lean.
        Functions using ``Int.fdiv`` need specialised tactics using
        ``Int.fdiv_mul_le`` and ``Int.lt_fdiv_add_one_mul_self``.
        """
        def _expr_uses_fdiv(expr: Optional[ExpressionIR]) -> bool:
            if expr is None:
                return False
            if expr.expr_type == "binary_op" and expr.op == "//":
                return True
            for attr in ("left", "right", "operand"):
                child = getattr(expr, attr, None)
                if child is not None and _expr_uses_fdiv(child):
                    return True
            return False
        def _stmt_uses_fdiv(stmt: StatementIR) -> bool:
            for attr in ("value", "expression", "condition"):
                expr = getattr(stmt, attr, None)
                if expr is not None and _expr_uses_fdiv(expr):
                    return True
            for s in stmt.body + stmt.orelse:
                if _stmt_uses_fdiv(s):
                    return True
            return False
        for stmt in func.body:
            if _stmt_uses_fdiv(stmt):
                return True
        return False

    def _get_nat_params(self, func: FunctionIR, func_name: str) -> set[str]:
        """Return the set of parameter names that should use ``\u2115`` instead of ``\u2124``.

        A parameter qualifies for ``\u2115`` when:
        1. The function is recursive (calls itself).
        2. There is a precondition ``param >= 0`` or ``param > 0`` (after stripping
           type-assertions like ``isinstance``).

        This lets recursive functions like ``factorial`` with ``@requires(lambda n: n >= 0)``
        generate well-founded Lean ``def``\u2019s over ``\u2115`` instead of ``\u2124``.
        """
        if not self._is_recursive(func):
            return set()

        nat_params: set[str] = set()

        # Gather preconditions for this function from the spec collection
        preconditions: List[str] = []
        if self._specs:
            for ob in self._specs.all:
                if ob.kind == ObligationKind.PRECONDITION and ob.function == func_name:
                    stripped = self._strip_type_assertions(ob.predicate)
                    if stripped and stripped not in ("and", "or", ""):
                        preconditions.append(stripped)

        if not preconditions:
            return set()

        pred_text = " ".join(preconditions)

        for param in func.signature.parameters:
            if param.type and param.type.name == "int":
                # Match param >= 0, param > 0, (param >= 0), etc.
                pattern = rf'\b{re.escape(param.name)}\s*(>=|>)\s*0\b'
                if re.search(pattern, pred_text):
                    nat_params.add(param.name)

        return nat_params

    # ── Helpers ───────────────────────────────────────────────────────────

    def _find_function(self, name: str) -> Optional[FunctionIR]:
        """Look up a FunctionIR by its (possibly dotted) name."""
        for func in (self._ir.functions if self._ir else []):
            if func.signature.name == name:
                return func
        if self._ir:
            for cls in self._ir.classes:
                for method in cls.methods:
                    if f"{cls.name}.{method.signature.name}" == name:
                        return method
        return None

    @staticmethod
    def _strip_type_assertions(predicate: str) -> str:
        """Strip isinstance/type calls from a predicate, keeping logical constraints.

        Handles deeply nested parenthesized structure from the spec parser:
        ``(((isinstance(x, int) and isinstance(lo, int)) and isinstance(hi, int)) and (lo <= hi))``
        returns ``lo <= hi``.

        Also handles the case where after removing isinstance calls, leftover artefacts
        like ``(( and ) and (b > 0))`` are cleaned down to ``b > 0``.
        """
        p = predicate.strip()

        # Remove isinstance/type calls (they never contain nested parens)
        lowered = re.sub(r'\bisinstance\s*\([^)]*\)', '', p, flags=re.IGNORECASE)
        lowered = re.sub(r'\btype\s*\([^)]*\)', '', lowered, flags=re.IGNORECASE)

        # Clean up: remove empty parentheses ``()`` or ``(  )``
        lowered = re.sub(r'\(\s*\)', '', lowered)

        # Clean up: remove stray `and`/`or` operators from collapsed structure.
        # This handles the ``( and ) ...`` pattern left after stripping isinstance
        # from chained comparisons like ``(isinstance(a, int) and (b > 0))``.
        lowered = re.sub(r'\s+(and|or)\s+(and|or)\s+', ' ', lowered)

        # Remove ``( and )`` and similar patterns: parenthesised stray operators
        lowered = re.sub(r'\(\s*and\s*\)', '', lowered)
        lowered = re.sub(r'\(\s*or\s*\)', '', lowered)

        # Remove leading/trailing operators and dangling parens
        lowered = re.sub(r'(^|[\s(])(and|or)\s+', ' ', lowered)
        lowered = re.sub(r'\s+(and|or)(\s|[)])$', ' ', lowered)

        # Remove ``) and (`` → ``) (`` → then collapse
        lowered = re.sub(r'\)\s+and\s+\(', ') (', lowered)

        # Final pass: remove any remaining isolated ``(`` or ``)`` that are adjacent
        # to whitespace (orphaned from the isinstance removal)
        lowered = re.sub(r'\(\s+\)', '', lowered)
        lowered = re.sub(r'\)\s+\(', '', lowered)

        # Flatten whitespace
        lowered = re.sub(r'\s+', ' ', lowered).strip()

        # Remove any remaining bare parens at edges
        lowered = lowered.strip('() \t')

        # Final cleanup: if the result is just an operator or empty, return ""
        lowered = lowered.strip()
        if lowered in ('and', 'or', '', '(', ')') or not lowered:
            return ""

        return lowered

    @staticmethod
    def _split_chained_comparisons(pred: str) -> str:
        """Split chained comparisons into a conjunction.

        Handles the spec parser's nested binary format ``((a <= b) <= c)``
        and produces ``(a ≤ b) ∧ (b ≤ c)``.

        Guards against false positives where compound operators like ``>=``
        are matched as two separate operators (``>`` + ``=``) with an empty
        middle term.
        """
        p = pred.strip()

        # Multi-character operators MUST come before single-character ones
        # to avoid matching ``<`` then ``=`` in ``<=``.
        ops = r'<=|>=|!=|\u2264|\u2265|\u2260|<|>|='

        # Match ((term1 op1 term2) op2 term3) — spec parser nested format
        m = re.match(
            r'^\(\((.+?)\s*(' + ops + r')\s*(.+?)\)\s*(' + ops + r')\s*(.+?)\)$',
            p
        )
        if m:
            t1, op1, t2, op2, t3 = m.groups()
            if t2.strip():
                return f"({t1.strip()} {op1.strip()} {t2.strip()}) \u2227 ({t2.strip()} {op2.strip()} {t3.strip()})"
            return pred

        # Flat format: term1 op1 term2 op2 term3 — only when NO logical
        # connectives (∧, ∨) are present in the predicate. This prevents false
        # matches where ``<`` and ``=`` appear in different sub-expressions
        # separated by ``∧`` or ``∨`` (e.g., ``(x < lo) ∧ (y = hi)``).
        if '\u2227' not in p and '\u2228' not in p \
           and ' and ' not in p.lower() and ' or ' not in p.lower():
            pattern = r'^(.*?)\s*(' + ops + r')\s*(.*?)\s*(' + ops + r')\s*(.*)$'
            m = re.match(pattern, p)
            if m:
                term1, op1, term2, op2, term3 = m.groups()
                # Guard: middle term must be non-empty to prevent splitting
                # compound operators (e.g., ``>=`` → ``>`` + ``=``).
                if term2.strip():
                    return f"({term1.strip()} {op1.strip()} {term2.strip()}) \u2227 ({term2.strip()} {op2.strip()} {term3.strip()})"

        return pred

    @staticmethod
    def _is_type_assertion(predicate: str) -> bool:
        """Return True if the predicate is a mere type assertion (e.g. isinstance(n, int)).

        Handles both simple calls like ``isinstance(x, int)`` and compound
        forms like ``(isinstance(a, int) and isinstance(b, int))``.
        """
        # Strip outer parentheses
        p = predicate.strip()
        while p.startswith("(") and p.endswith(")"):
            inner = p[1:-1].strip()
            if inner.count("(") == inner.count(")"):
                p = inner
            else:
                break

        # Check for single isinstance/type call
        lowered = p.lower()
        if lowered.startswith("isinstance(") or lowered.startswith("type("):
            return True

        # Check for compound condition made up entirely of isinstance/type calls
        # joined by ``and``/``or`` (possibly nested in parentheses).
        stripped = re.sub(
            r'\bisinstance\s*\([^)]*\)', '', lowered
        )
        stripped = re.sub(
            r'\btype\s*\([^)]*\)', '', stripped
        )
        # Remove any remaining whitespace and logical tokens
        stripped = stripped.replace(' ', '').replace('and', '')  \
                          .replace('or', '').replace('(', '')   \
                          .replace(')', '').strip()
        return stripped == ''

    # ── Expression translation ────────────────────────────────────────────

    def translate_expression(self, expr: ExpressionIR) -> str:
        if expr is None:
            return "True"
        dispatch = {
            "constant": lambda e: self._translate_constant(e.value),
            "variable": lambda e: e.name,
            "binary_op": self._translate_binary_op,
            "unary_op": self._translate_unary_op,
            "call": self._translate_call,
            "attribute": self._translate_attribute,
            "subscript": self._translate_subscript,
            "list": self._translate_list,
            "if_exp": self._translate_if_exp,
        }
        handler = dispatch.get(expr.expr_type)
        if handler:
            return handler(expr)
        return "True"

    def _translate_constant(self, value: Any) -> str:
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, int):
            return str(value)
        if isinstance(value, float):
            return f"({value} : \u211d)" if value != int(value) else f"({int(value)} : \u211d)"
        if isinstance(value, str):
            return f'"{value}"'
        if value is None:
            return "none"
        return str(value)

    def _translate_binary_op(self, expr: ExpressionIR) -> str:
        left = self.translate_expression(expr.left) if expr.left else "?"
        right = self.translate_expression(expr.right) if expr.right else "?"
        # Python's ``//`` is floor division, which maps to ``Int.fdiv`` in Lean/Mathlib.
        # Regular ``/`` in Lean on \u2124 is truncating division (toward zero), which differs
        # from Python floor division for negative numbers.
        if expr.op == "//":
            return f"(Int.fdiv {left} {right})"
        op = _BINOP_TO_LEAN.get(expr.op, f" {expr.op} ")
        return f"({left}{op}{right})"

    def _translate_unary_op(self, expr: ExpressionIR) -> str:
        operand = self.translate_expression(expr.operand) if expr.operand else "?"
        op = _UNOP_TO_LEAN.get(expr.op, expr.op)
        return f"({op}{operand})"

    def _translate_call(self, expr: ExpressionIR) -> str:
        func_name = ""
        if expr.func:
            func_name = self.translate_expression(expr.func)
        args = [self.translate_expression(a) for a in expr.args]
        name = func_name.lower()

        if name in ("abs",):
            return f"(abs {args[0]})" if args else "(abs ?_)"
        if name in ("len",):
            return f"({args[0]}.length)" if args else "(?_.length)"
        if name in ("max", "min"):
            return f"({name} {args[0]} {args[1]})" if len(args) >= 2 else f"({name} {args[0]})"
        if name in ("range",):
            return f"(Finset.range {args[0]})" if args else "(Finset.range ?_)"
        if name in ("int", "float", "str", "bool"):
            return args[0] if args else "?"
        if func_name:
            return f"({func_name} {' '.join(args)})"
        return f"(? {', '.join(args)})" if args else "?"

    def _translate_attribute(self, expr: ExpressionIR) -> str:
        target = self.translate_expression(expr.target) if expr.target else "?"
        attr_map = {"shape": f"({target}.shape)", "length": f"({target}.length)", "T": f"({target}.transpose)"}
        return attr_map.get(expr.attr, f"({target}.{expr.attr})")

    def _translate_subscript(self, expr: ExpressionIR) -> str:
        target = self.translate_expression(expr.target) if expr.target else "?"
        index = self.translate_expression(expr.index) if expr.index else "?"
        return f"({target}[{index}])"

    def _translate_list(self, expr: ExpressionIR) -> str:
        elements = [self.translate_expression(e) for e in expr.elements]
        return f"[{', '.join(elements)}]"

    def _translate_if_exp(self, expr: ExpressionIR) -> str:
        condition = self.translate_expression(expr.left) if expr.left else "?"
        then_expr = self.translate_expression(expr.right) if expr.right else "?"
        else_expr = self.translate_expression(expr.operand) if expr.operand else "?"
        return f"(if {condition} then {then_expr} else {else_expr})"

    # ── Type translation ──────────────────────────────────────────────────

    def translate_type(self, py_type: str) -> str:
        """Translate a Python type string to a Lean 4 type string."""
        py_type = py_type.strip()
        if not py_type:
            return "\u2124"
        if "[" in py_type and py_type.endswith("]"):
            base = py_type[: py_type.index("[")]
            inner = py_type[py_type.index("[") + 1: -1]
            base_lean = _PY_TYPE_TO_LEAN.get(base, base)
            inner_lean = self.translate_type(inner)
            return f"{base_lean} {inner_lean}"
        return _PY_TYPE_TO_LEAN.get(py_type, py_type)

    # ── Utility ───────────────────────────────────────────────────────────

    @staticmethod
    def obligation_to_predicate_lean(ob: ProofObligation) -> str:
        """Convert a proof obligation's predicate to a Lean 4 proposition string."""
        pred = ob.predicate.strip()
        # Order matters: longer operators (<=, >=) before shorter ones (<, >)
        replacements = [
            ("<=", " \u2264 "), (">=", " \u2265 "),
            ("==", "="), ("!=", " \u2260 "),
            (" and ", " \u2227 "), (" or ", " \u2228 "),
            ("not ", "\u00ac "), ("True", "true"), ("False", "false"),
        ]
        for old, new in replacements:
            pred = pred.replace(old, new)
        return re.sub(r'\s+', ' ', pred).strip()

    @staticmethod
    def _generate_induction_tactic(func_name: str, param: str) -> str:
        """Generate an induction-based tactic for recursive \u2115 functions with comparison goals.

        ``omega`` cannot handle recursive definitions, so we use structural
        induction on the \u2115 parameter. The generated tactic is::

            induction n with
            | zero => unfold foo; simp
            | succ n ih => unfold foo; split_ifs <;> nlinarith

        ``nlinarith`` can handle the non-linear arithmetic that arises from
        multiplication in the recursive body (e.g., ``(n+1) * factorial n >= 1``).
        """
        return (
            f"induction {param} with\n"
            f"| zero => unfold {func_name}; simp\n"
            f"| succ {param} ih => unfold {func_name}; split_ifs <;> simp [Nat.succ_sub_succ, Nat.sub_zero] <;> nlinarith"
        )

    @staticmethod
    def _generate_cases_tactic(func_name: str, param: str) -> str:
        """Generate a case-analysis tactic for recursive \u2115 functions with disjunction goals.

        For goals like ``(n = 0) \u2228 (factorial n = n * factorial(n - 1))``,
        case analysis on the \u2115 parameter is more robust than ``split_ifs``::

            cases n with
            | zero => left; rfl
            | succ n => right; simp [func_name]
        """
        return (
            f"cases {param} with\n"
            f"| zero => left; rfl\n"
            f"| succ {param} => right; simp [{func_name}]"
        )

    @staticmethod
    def _format_proof_block(tactic: str) -> str:
        return f"  by\n    {tactic}"
